trigger: none

pool:
  name: avriti   # आपका self-hosted Windows agent

steps:

# 🔹 Install Terraform
- task: TerraformInstaller@1
  displayName: "Install Terraform CLI"
  inputs:
    terraformVersion: 'latest'


# 🔹 Terraform Format
- script: |
    echo Running Terraform Format
    terraform fmt -recursive
  displayName: "Terraform Format Check"


# 🔹 Terraform Init
- task: TerraformTask@5
  displayName: "Terraform Init (Backend Setup)"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'avtsrv'
    backendAzureRmOverrideSubscriptionID: '18ed265f-7186-4239-bed6-23429dea97a7'
    backendAzureRmResourceGroupName: 'backendtest'
    backendAzureRmStorageAccountName: 'akhileshtest'
    backendAzureRmContainerName: 'canttest'
    backendAzureRmKey: 'pipe.tfstate'


# 🔹 Terraform Validate
- script: |
    echo Running Terraform Validate
    terraform validate
  displayName: "Terraform Validate"


# 🔹 Install TFsec (Windows)
- powershell: |

    Write-Host "Installing TFsec"

    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    Invoke-WebRequest `
    -Uri "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.exe" `
    -OutFile "C:\tfsec.exe"

    echo "##vso[task.prependpath]C:\"

    Write-Host "TFsec Installation Completed"

    tfsec.exe --version

  displayName: "Install TFsec (Windows)"


# 🔹 Run TFsec Security Scan
- powershell: |

    Write-Host "Running TFsec Security Scan"

    tfsec.exe .

  displayName: "Terraform Security Scan"


# 🔹 Terraform Plan
- task: TerraformTask@5
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'avtsrv'


# 🔹 Terraform Apply (Optional)
# - task: TerraformTask@5
#   displayName: "Terraform Apply"
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     environmentServiceNameAzureRM: 'avtsrv'
#     commandOptions: '-auto-approve'