trigger: none

pool:
  name: avriti   # Self-hosted Windows Agent

steps:

# 🔹 Install Terraform
- task: TerraformInstaller@1
  displayName: "Install Terraform CLI"
  inputs:
    terraformVersion: 'latest'


# 🔹 Terraform Format
- powershell: |
    Write-Host "Running Terraform Format"

    terraform fmt -recursive

  displayName: "Terraform Format"


# 🔹 Terraform Init (Backend Setup)
- task: TerraformTask@5
  displayName: "Terraform Init"
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'avtsrv'
    backendAzureRmOverrideSubscriptionID: '18ed265f-7186-4239-bed6-23429dea97a7'
    backendAzureRmResourceGroupName: 'backendtest'
    backendAzureRmStorageAccountName: 'akhileshtest'
    backendAzureRmContainerName: 'canttest'
    backendAzureRmKey: 'pipe.tfstate'


# 🔹 Terraform Validate
- powershell: |
    Write-Host "Running Terraform Validate"

    terraform validate

  displayName: "Terraform Validate"


# 🔹 Install TFsec
- powershell: |

    Write-Host "Installing TFsec"

    [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

    $tfsecPath = "$(Agent.TempDirectory)\tfsec.exe"

    Invoke-WebRequest `
    -Uri "https://github.com/aquasecurity/tfsec/releases/latest/download/tfsec-windows-amd64.exe" `
    -OutFile $tfsecPath `
    -UseBasicParsing


    echo "##vso[task.prependpath]$(Agent.TempDirectory)"

    Write-Host "TFsec Installed"

    tfsec.exe --version


  displayName: "Install TFsec"


# 🔹 Terraform Security Scan
- powershell: |

    Write-Host "Running TFsec Security Scan"

    tfsec.exe .

  displayName: "Terraform Security Scan"


# 🔹 Terraform Plan
- task: TerraformTask@5
  displayName: "Terraform Plan"
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'avtsrv'
    commandOptions: '-out=tfplan'


# 🔹 Terraform Apply
- task: TerraformTask@5
  displayName: "Terraform Apply"
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'avtsrv'
    commandOptions: 'tfplan'